/*
Deployment script for MYahitophel

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "MYahitophel"
:setvar DefaultFilePrefix "MYahitophel"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[AddressEmployee]...';


GO
CREATE TABLE [dbo].[AddressEmployee] (
    [EmployeeID]  INT           NOT NULL,
    [AddressCode] INT           NULL,
    [Address]     NVARCHAR (50) NULL,
    [City]        NVARCHAR (15) NULL,
    [PostalCode]  NVARCHAR (10) NULL,
    [Country]     NVARCHAR (15) NULL
);


GO
PRINT N'Creating Table [dbo].[Black_List]...';


GO
CREATE TABLE [dbo].[Black_List] (
    [CompanyID]  INT      NOT NULL,
    [Start_Date] DATETIME NULL,
    [End_Date]   DATETIME NULL
);


GO
PRINT N'Creating Table [dbo].[Children_Of_Senior_Managers]...';


GO
CREATE TABLE [dbo].[Children_Of_Senior_Managers] (
    [ChildSeniorID_num] INT           NOT NULL,
    [SeniorID]          INT           NOT NULL,
    [FirstName]         NVARCHAR (20) NOT NULL,
    [LastName]          NVARCHAR (20) NOT NULL,
    [BirthDate]         DATETIME      NULL,
    CONSTRAINT [PK_Children_Of_Senior_Managers] PRIMARY KEY CLUSTERED ([ChildSeniorID_num] ASC),
    CONSTRAINT [UQ__Children__BEFA07373BFE6181] UNIQUE NONCLUSTERED ([SeniorID] ASC)
);


GO
PRINT N'Creating Table [dbo].[ChildrenOfEmployee]...';


GO
CREATE TABLE [dbo].[ChildrenOfEmployee] (
    [ChildID_num] INT           NOT NULL,
    [FirstName]   NVARCHAR (20) NOT NULL,
    [LastName]    NVARCHAR (20) NOT NULL,
    [EmployeeID]  INT           NOT NULL,
    [BirthDate]   DATETIME      NULL,
    [Address]     NVARCHAR (50) NULL,
    [City]        NVARCHAR (15) NULL,
    [PostalCode]  NVARCHAR (10) NULL,
    [Country]     NVARCHAR (15) NULL,
    CONSTRAINT [PK_ChildrenOfEmployee] PRIMARY KEY CLUSTERED ([ChildID_num] ASC),
    UNIQUE NONCLUSTERED ([ChildID_num] ASC)
);


GO
PRINT N'Creating Table [dbo].[CurrencyHistory]...';


GO
CREATE TABLE [dbo].[CurrencyHistory] (
    [DateCurrency] DATE          NOT NULL,
    [DollarRate]   NVARCHAR (1)  NOT NULL,
    [ValidFrom]    DATETIME2 (2) NOT NULL,
    [ValidTo]      DATETIME2 (2) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[CurrencyHistory].[ix_MSSQL_TemporalHistoryFor_242099903]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_242099903]
    ON [dbo].[CurrencyHistory]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[Customer_Invoices]...';


GO
CREATE TABLE [dbo].[Customer_Invoices] (
    [CompanyID]            INT      NOT NULL,
    [Invoice_Amount]       INT      NOT NULL,
    [Issue_Date]           DATETIME NOT NULL,
    [Last_date_of_Payment] DATETIME NOT NULL,
    [Date_of_Payment]      DATETIME NULL
);


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [CompanyID]       INT           IDENTITY (4568, 3) NOT NULL,
    [CompanyName]     NVARCHAR (40) NOT NULL,
    [CountryOfOrigin] NVARCHAR (30) NOT NULL,
    [Main_Phone]      NVARCHAR (20) NULL,
    [Black_List]      NCHAR (10)    NULL,
    [TeamID]          INT           NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CompanyID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Customers_Address]...';


GO
CREATE TABLE [dbo].[Customers_Address] (
    [CompanyID]  INT           NOT NULL,
    [Address]    NVARCHAR (50) NULL,
    [City]       NVARCHAR (15) NULL,
    [PostalCode] NVARCHAR (10) NULL,
    [Country]    NVARCHAR (15) NULL
);


GO
PRINT N'Creating Table [dbo].[Employee_Hearing]...';


GO
CREATE TABLE [dbo].[Employee_Hearing] (
    [EmployeeID]    INT           NOT NULL,
    [Hearing_Date]  DATETIME      NULL,
    [Dismissal_Y_N] NVARCHAR (20) NOT NULL,
    [Note]          NVARCHAR (20) NULL
);


GO
PRINT N'Creating Table [dbo].[Employees]...';


GO
CREATE TABLE [dbo].[Employees] (
    [EmployeeID]        INT           NOT NULL,
    [ID_num]            INT           NOT NULL,
    [FirstName]         NVARCHAR (20) NOT NULL,
    [LastName]          NVARCHAR (20) NOT NULL,
    [BirthDate]         DATETIME      NULL,
    [Marital_Status]    NCHAR (10)    NULL,
    [SpouseID]          NVARCHAR (20) NULL,
    [Gender]            NVARCHAR (20) NULL,
    [Num_of_children18] INT           NULL,
    [TeamID]            INT           NOT NULL,
    [Manager]           NCHAR (10)    NULL,
    [Hire_Date]         DATETIME      NOT NULL,
    [End_Of_Hire_Date]  DATETIME      NULL,
    [Salary]            MONEY         NOT NULL,
    [Social]            NCHAR (10)    NOT NULL,
    CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    CONSTRAINT [UQ__Employee__7AD04FF0459E0454] UNIQUE NONCLUSTERED ([EmployeeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Employees_projects]...';


GO
CREATE TABLE [dbo].[Employees_projects] (
    [ProjectID] INT NOT NULL,
    [TeamID]    INT NOT NULL,
    CONSTRAINT [PK_Employees_projects_1] PRIMARY KEY CLUSTERED ([ProjectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Holiday]...';


GO
CREATE TABLE [dbo].[Holiday] (
    [HolidayID]    INT           IDENTITY (1, 1) NOT NULL,
    [Holiday_Name] NVARCHAR (20) NOT NULL,
    [Holiday_Date] DATETIME      NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Hours_Report]...';


GO
CREATE TABLE [dbo].[Hours_Report] (
    [EmployeeID]    INT        NOT NULL,
    [ProjectID]     INT        NOT NULL,
    [CompanyName]   NCHAR (10) NOT NULL,
    [Starting_Hour] DATETIME   NOT NULL,
    [Ending_hour]   DATETIME   NOT NULL,
    [City]          NCHAR (10) NULL,
    CONSTRAINT [PK_Hours_Report] PRIMARY KEY CLUSTERED ([EmployeeID] ASC, [ProjectID] ASC, [Starting_Hour] ASC)
);


GO
PRINT N'Creating Table [dbo].[Inquiry_Call]...';


GO
CREATE TABLE [dbo].[Inquiry_Call] (
    [EmployeeID]   INT           NOT NULL,
    [Inquiry_Date] DATETIME      NULL,
    [hearing_Y_N]  NCHAR (10)    NULL,
    [Note]         NVARCHAR (20) NULL
);


GO
PRINT N'Creating Table [dbo].[Project_Manager]...';


GO
CREATE TABLE [dbo].[Project_Manager] (
    [ManagerID]     INT           NOT NULL,
    [FirstName]     NVARCHAR (20) NOT NULL,
    [LastName]      NVARCHAR (20) NOT NULL,
    [CompanyID]     INT           NOT NULL,
    [BirthDate]     DATETIME      NULL,
    [Address]       NVARCHAR (50) NULL,
    [City]          NVARCHAR (15) NULL,
    [PostalCode]    NVARCHAR (10) NULL,
    [Country]       NVARCHAR (15) NULL,
    [Favorite_cake] NVARCHAR (30) NULL,
    [Phone]         NVARCHAR (20) NULL,
    [Caketype]      NCHAR (20)    NULL,
    CONSTRAINT [PK_Project_Manager] PRIMARY KEY CLUSTERED ([ManagerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Projects]...';


GO
CREATE TABLE [dbo].[Projects] (
    [ProjectID]       INT           IDENTITY (1234, 3) NOT NULL,
    [CompanyID]       INT           NOT NULL,
    [TeamID]          INT           NOT NULL,
    [ManagerID]       INT           NOT NULL,
    [Order_Date]      DATETIME      NULL,
    [Project_Status]  NVARCHAR (20) NULL,
    [City]            NCHAR (10)    NOT NULL,
    [Black_List]      NCHAR (10)    NULL,
    [Consultant_Cost] INT           NOT NULL,
    [Travel_Cost]     MONEY         NOT NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED ([ProjectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Senior_Project_Managers]...';


GO
CREATE TABLE [dbo].[Senior_Project_Managers] (
    [SeniorID]      INT           NOT NULL,
    [FirstName]     NVARCHAR (20) NOT NULL,
    [LastName]      NVARCHAR (20) NOT NULL,
    [ProjectID]     INT           NOT NULL,
    [BirthDate]     DATETIME      NULL,
    [Address]       NVARCHAR (50) NULL,
    [City]          NVARCHAR (15) NULL,
    [PostalCode]    NVARCHAR (10) NULL,
    [Country]       NVARCHAR (15) NULL,
    [Phone]         NVARCHAR (20) NULL,
    [Favorite_cake] NVARCHAR (30) NULL,
    CONSTRAINT [PK_Senior_Project_Managers] PRIMARY KEY CLUSTERED ([SeniorID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Spouse_Of_Employee]...';


GO
CREATE TABLE [dbo].[Spouse_Of_Employee] (
    [SpouseID_num] INT           NOT NULL,
    [FirstName]    NVARCHAR (20) NOT NULL,
    [LastName]     NVARCHAR (20) NOT NULL,
    [EmployeeID]   INT           NOT NULL,
    [BirthDate]    DATETIME      NULL,
    [Genus]        NVARCHAR (20) NULL,
    [Address]      NVARCHAR (50) NULL,
    [City]         NVARCHAR (15) NULL,
    [PostalCode]   NVARCHAR (10) NULL,
    [Country]      NVARCHAR (15) NULL,
    CONSTRAINT [PK_SpouseOfEmployee] PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    UNIQUE NONCLUSTERED ([SpouseID_num] ASC)
);


GO
PRINT N'Creating Table [dbo].[Spouse_Project_Manager]...';


GO
CREATE TABLE [dbo].[Spouse_Project_Manager] (
    [SpouseID_num] INT           NOT NULL,
    [FirstName]    NVARCHAR (20) NOT NULL,
    [LastName]     NVARCHAR (20) NOT NULL,
    [SeniorID]     INT           NOT NULL,
    [BirthDate]    DATETIME      NULL,
    [Genus]        NVARCHAR (20) NULL,
    [Address]      NVARCHAR (50) NULL,
    [City]         NVARCHAR (15) NULL,
    [PostalCode]   NVARCHAR (10) NULL,
    [Country]      NVARCHAR (15) NULL,
    [CakeID]       INT           NULL,
    CONSTRAINT [PK_Spouse_Project_Manager] PRIMARY KEY CLUSTERED ([SpouseID_num] ASC),
    UNIQUE NONCLUSTERED ([SpouseID_num] ASC)
);


GO
PRINT N'Creating Table [dbo].[TeamProjectCost]...';


GO
CREATE TABLE [dbo].[TeamProjectCost] (
    [ProjectID] INT          NOT NULL,
    [teamID]    INT          NOT NULL,
    [cost]      NVARCHAR (1) NOT NULL,
    PRIMARY KEY CLUSTERED ([ProjectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [TeamID]      INT IDENTITY (100, 100) NOT NULL,
    [Team_leader] INT NOT NULL,
    [EmployeeID]  INT NOT NULL,
    CONSTRAINT [PK_Teams] PRIMARY KEY CLUSTERED ([EmployeeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[TypeAddress]...';


GO
CREATE TABLE [dbo].[TypeAddress] (
    [AddressCode]   INT           NOT NULL,
    [TypeOfAddress] NVARCHAR (10) NULL,
    CONSTRAINT [PK_TypeAddress] PRIMARY KEY CLUSTERED ([AddressCode] ASC),
    UNIQUE NONCLUSTERED ([AddressCode] ASC)
);


GO
PRINT N'Creating Table [dbo].[Variables_History]...';


GO
CREATE TABLE [dbo].[Variables_History] (
    [parameter] NVARCHAR (30) NOT NULL,
    [varible]   FLOAT (53)    NOT NULL,
    [ValidFrom] DATETIME2 (2) NOT NULL,
    [ValidTo]   DATETIME2 (2) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[Variables_History].[ix_MSSQL_TemporalHistoryFor_162099618]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_162099618]
    ON [dbo].[Variables_History]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[Currency]...';


GO
CREATE TABLE [dbo].[Currency] (
    [DateCurrency] DATE                                               NOT NULL,
    [DollarRate]   NVARCHAR (1)                                       NOT NULL,
    [ValidFrom]    DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [ValidTo]      DATETIME2 (2) GENERATED ALWAYS AS ROW END          NOT NULL,
    PRIMARY KEY CLUSTERED ([DateCurrency] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[CurrencyHistory], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[Variables]...';


GO
CREATE TABLE [dbo].[Variables] (
    [parameter] NVARCHAR (30)                               NOT NULL,
    [varible]   FLOAT (53)                                  NOT NULL,
    [ValidFrom] DATETIME2 (2) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]   DATETIME2 (2) GENERATED ALWAYS AS ROW END   NOT NULL,
    PRIMARY KEY CLUSTERED ([parameter] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[Variables_History], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[AddressEmployee]...';


GO
ALTER TABLE [dbo].[AddressEmployee]
    ADD DEFAULT ((1)) FOR [AddressCode];


GO
PRINT N'Creating Foreign Key [dbo].[FK_AddressEmployee_Employees1]...';


GO
ALTER TABLE [dbo].[AddressEmployee] WITH NOCHECK
    ADD CONSTRAINT [FK_AddressEmployee_Employees1] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AddressEmployee_TypeAddress]...';


GO
ALTER TABLE [dbo].[AddressEmployee] WITH NOCHECK
    ADD CONSTRAINT [FK_AddressEmployee_TypeAddress] FOREIGN KEY ([AddressCode]) REFERENCES [dbo].[TypeAddress] ([AddressCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Black_List_Customers]...';


GO
ALTER TABLE [dbo].[Black_List] WITH NOCHECK
    ADD CONSTRAINT [FK_Black_List_Customers] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Customers] ([CompanyID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ChildrenOfEmployee_Employees]...';


GO
ALTER TABLE [dbo].[ChildrenOfEmployee] WITH NOCHECK
    ADD CONSTRAINT [FK_ChildrenOfEmployee_Employees] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Customer_Invoices_Customers]...';


GO
ALTER TABLE [dbo].[Customer_Invoices] WITH NOCHECK
    ADD CONSTRAINT [FK_Customer_Invoices_Customers] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Customers] ([CompanyID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Customers_Teams]...';


GO
ALTER TABLE [dbo].[Customers] WITH NOCHECK
    ADD CONSTRAINT [FK_Customers_Teams] FOREIGN KEY ([TeamID]) REFERENCES [dbo].[Teams] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Company_Address_Customers]...';


GO
ALTER TABLE [dbo].[Customers_Address] WITH NOCHECK
    ADD CONSTRAINT [FK_Company_Address_Customers] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Customers] ([CompanyID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Employee_Hearing_Employees]...';


GO
ALTER TABLE [dbo].[Employee_Hearing] WITH NOCHECK
    ADD CONSTRAINT [FK_Employee_Hearing_Employees] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Hours_Report_Projects]...';


GO
ALTER TABLE [dbo].[Hours_Report] WITH NOCHECK
    ADD CONSTRAINT [FK_Hours_Report_Projects] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[Projects] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Inquiry_Call_Employees]...';


GO
ALTER TABLE [dbo].[Inquiry_Call] WITH NOCHECK
    ADD CONSTRAINT [FK_Inquiry_Call_Employees] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Customers]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Customers] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Customers] ([CompanyID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_TeamProjectCost]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_TeamProjectCost] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[TeamProjectCost] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Senior_Project_Managers_Children_Of_Senior_Managers1]...';


GO
ALTER TABLE [dbo].[Senior_Project_Managers] WITH NOCHECK
    ADD CONSTRAINT [FK_Senior_Project_Managers_Children_Of_Senior_Managers1] FOREIGN KEY ([SeniorID]) REFERENCES [dbo].[Children_Of_Senior_Managers] ([SeniorID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Senior_Project_Managers_Project_Manager]...';


GO
ALTER TABLE [dbo].[Senior_Project_Managers] WITH NOCHECK
    ADD CONSTRAINT [FK_Senior_Project_Managers_Project_Manager] FOREIGN KEY ([SeniorID]) REFERENCES [dbo].[Project_Manager] ([ManagerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Senior_Project_Managers_Projects]...';


GO
ALTER TABLE [dbo].[Senior_Project_Managers] WITH NOCHECK
    ADD CONSTRAINT [FK_Senior_Project_Managers_Projects] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[Projects] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SpouseOfEmployee_Employees]...';


GO
ALTER TABLE [dbo].[Spouse_Of_Employee] WITH NOCHECK
    ADD CONSTRAINT [FK_SpouseOfEmployee_Employees] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Spouse_Project_Manager_Senior_Project_Managers]...';


GO
ALTER TABLE [dbo].[Spouse_Project_Manager] WITH NOCHECK
    ADD CONSTRAINT [FK_Spouse_Project_Manager_Senior_Project_Managers] FOREIGN KEY ([SeniorID]) REFERENCES [dbo].[Senior_Project_Managers] ([SeniorID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TeamProjectCost_Teams]...';


GO
ALTER TABLE [dbo].[TeamProjectCost] WITH NOCHECK
    ADD CONSTRAINT [FK_TeamProjectCost_Teams] FOREIGN KEY ([teamID]) REFERENCES [dbo].[Teams] ([EmployeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Teams_Employees]...';


GO
ALTER TABLE [dbo].[Teams] WITH NOCHECK
    ADD CONSTRAINT [FK_Teams_Employees] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Creating Extended Property [dbo].[Employees].[ID_num].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Employees', @level2type = N'COLUMN', @level2name = N'ID_num';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[AddressEmployee] WITH CHECK CHECK CONSTRAINT [FK_AddressEmployee_Employees1];

ALTER TABLE [dbo].[AddressEmployee] WITH CHECK CHECK CONSTRAINT [FK_AddressEmployee_TypeAddress];

ALTER TABLE [dbo].[Black_List] WITH CHECK CHECK CONSTRAINT [FK_Black_List_Customers];

ALTER TABLE [dbo].[ChildrenOfEmployee] WITH CHECK CHECK CONSTRAINT [FK_ChildrenOfEmployee_Employees];

ALTER TABLE [dbo].[Customer_Invoices] WITH CHECK CHECK CONSTRAINT [FK_Customer_Invoices_Customers];

ALTER TABLE [dbo].[Customers] WITH CHECK CHECK CONSTRAINT [FK_Customers_Teams];

ALTER TABLE [dbo].[Customers_Address] WITH CHECK CHECK CONSTRAINT [FK_Company_Address_Customers];

ALTER TABLE [dbo].[Employee_Hearing] WITH CHECK CHECK CONSTRAINT [FK_Employee_Hearing_Employees];

ALTER TABLE [dbo].[Hours_Report] WITH CHECK CHECK CONSTRAINT [FK_Hours_Report_Projects];

ALTER TABLE [dbo].[Inquiry_Call] WITH CHECK CHECK CONSTRAINT [FK_Inquiry_Call_Employees];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Customers];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_TeamProjectCost];

ALTER TABLE [dbo].[Senior_Project_Managers] WITH CHECK CHECK CONSTRAINT [FK_Senior_Project_Managers_Children_Of_Senior_Managers1];

ALTER TABLE [dbo].[Senior_Project_Managers] WITH CHECK CHECK CONSTRAINT [FK_Senior_Project_Managers_Project_Manager];

ALTER TABLE [dbo].[Senior_Project_Managers] WITH CHECK CHECK CONSTRAINT [FK_Senior_Project_Managers_Projects];

ALTER TABLE [dbo].[Spouse_Of_Employee] WITH CHECK CHECK CONSTRAINT [FK_SpouseOfEmployee_Employees];

ALTER TABLE [dbo].[Spouse_Project_Manager] WITH CHECK CHECK CONSTRAINT [FK_Spouse_Project_Manager_Senior_Project_Managers];

ALTER TABLE [dbo].[TeamProjectCost] WITH CHECK CHECK CONSTRAINT [FK_TeamProjectCost_Teams];

ALTER TABLE [dbo].[Teams] WITH CHECK CHECK CONSTRAINT [FK_Teams_Employees];


GO
PRINT N'Update complete.';


GO
